# Generated by Django 6.0.1 on 2026-02-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_refreshtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
